### ISSUE TITLE
Failed to insert Ubuntu CVE data.

### ISSUE THREAD

**Issue by tokyowizard** [vulsio/gost#101]
# What did you do? (required. The issue will be **closed** when not provided.)

```
gost fetch ubuntu --dbpath postgres://USER:PASSWORD@POSTGRESHOST:5432/gost?sslmode=disable --dbtype postgres
```
Note: Replaced values for `USER:PASSWORD@POSTGRESHOST`.

# What did you expect to happen?
gost would insert all of the data into the PostgreSQL database.

# What happened instead?
Failed to insert all of the data into the PostgreSQL database.

* Current Output

```
err: Failed to insert Ubuntu CVE data. err: Failed to insert. err: ERROR: value too long for type character varying(255) (SQLSTATE 22001)
```

Please re-run the command using ```-debug``` and provide the output below.

```
/gost # gost fetch ubuntu --dbpath postgres://USER:PASSWORD@POSTGRESHOST:5432/gost?sslmode=disable --dbtype postgres --debug
DBUG[01-04|10:01:34] git pull
DBUG[01-04|10:01:36] Ubuntu updated files: 38776
INFO[01-04|10:01:46] Initialize Database
INFO[01-04|10:01:46] Fetched                                  CVEs=38601
INFO[01-04|10:01:46] Insert Ubuntu into DB                    db=postgres
26745 / 38601 [----------------------------------------------------------------------------------------------------------------------------------------------------------------------->__________________________________________________________________________] 69.29% 449 p/sFailed to insert. dbpath: postgres://USER:PASSWORD@POSTGRESHOST:5432/gost?sslmode=disable, err: Failed to insert Ubuntu CVE data. err: Failed to insert. err: ERROR: value too long for type character varying(255) (SQLSTATE 22001)
/gost #
```

# Steps to reproduce the behaviour

1. I used this docker version:
```
$ docker --version
Docker version 20.10.11, build dea9396
```

2. Copy/paste these 2 files into an empty directory. Put the `initdb.sh` into a `postgres-scripts` subdirectory. Click the right triangle to expand and view the contents.

<details><summary> `docker-compose.yaml` </summary>

```
version: "3.9"
services:
  postgres:
    image: postgres:13.5-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password
    volumes:
      - type: bind
        source: postgres-scripts
        target: /docker-entrypoint-initdb.d

  gost:
    depends_on:
      - postgres
    image: vuls/gost@sha256:5177e78c9bd29eac8901bd109e455473ec81beb5796f951f8787e6d3fb55c8ae
    entrypoint:
      - /bin/sh
      - -c
    command:
      - "gost fetch ubuntu --dbpath postgres://gostuser:password@postgres:5432/gostdb?sslmode=disable --dbtype postgres"
```

</details>

<details><summary> `initdb.sh` </summary>

```
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
    CREATE USER gostuser PASSWORD 'password';
    CREATE DATABASE gostdb;
    GRANT ALL PRIVILEGES ON DATABASE gostdb TO gostuser;
EOSQL
```

</details>

So your directory structure looks like this:
```
.
├── docker-compose.yaml
└── postgres-scripts
    └── initdb.sh

1 directory, 2 files
```
And make the script executable:
```
chmod +x postgres-scripts/initdb.sh
```

3. In the same directory as `docker-compose.yaml`, run:
```
docker compose up -d
```
If you're on Linux and don't have the compose command, you'll need to add the [compose plugin](https://github.com/docker/compose/releases/tag/v2.2.2). Below I added instructions on how to add it.

<details><summary>How to add the compose plugin on Linux.</summary>

```
mkdir -p ~/.docker/cli-plugins
curl -sSL https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-$(uname -m) -o ~/.docker/cli-plugins/docker-compose
chmod +x ~/.docker/cli-plugins/docker-compose
```

</details>

4. Observe the error message by running the command below. It may take a minute or so for output to show:
```
docker compose logs -f gost
```

# Configuration (**MUST** fill this out):

* gost environment:

I used the current `latest` image with this sha:
https://hub.docker.com/layers/vuls/gost/latest/images/sha256-5177e78c9bd29eac8901bd109e455473ec81beb5796f951f8787e6d3fb55c8ae?context=explore

EDIT: Add instructions for adding the compose plugin for Linux + making the `initdb.sh` script executable.
